### ISSUE TITLE
ChangeScribe not describing all files

### ISSUE THREAD

**Issue by TomaszGaweda** [SEMERU-WM/ChangeScribe#1]
As mentioned previously in email, it seems that ChangeScribe in not describing all files.

We have tried:
- version from revision 1e82af7830d65d41965239ec0f8f8eb794f11ce0 (2014 year)
- current version

We are using current version of ChangeDistiller.
We have tried to use ChangeScribe installed on Eclipse Juno and in standalone (shell) mode. 

I see two different behaviours:
1. I created new example project, after changes there was 1 file added, 1 untracked and 1 modified. ChangeScribe is giving us following description: "Initial commit. This commit  includes changes to internationalization, properties or configuration files (pom.xml). ".
   ![cs_bug_new_project](https://cloud.githubusercontent.com/assets/8236272/11607949/acbba24e-9b5b-11e5-9b77-a2b1832739ff.png)
2. I imported old project, made some changes, ChangeScribe description is: "BUG - FEATURE: <type-ID> ", without mentioning of the files.

![cs_bug_existing](https://cloud.githubusercontent.com/assets/8236272/11607952/b109ea36-9b5b-11e5-9166-48ca0ab98048.png)

Filter factor was tested on various values (0.1, 0.2, ..0, 1). I have also tried to disable filter factor, but it didn't help. As far as I have debugged, JGit is returning proper list of changes, however somewhere most of entries got lost.

Steps to reproduce:
1. Download newest version of ChangeDistiller, build it (to have in local repository)
2. Download ChangeScribe
3. in build.properties change iconsold -> icons and in JParser constructor add (to support Java 8):
        @SuppressWarnings("rawtypes")
        Map options = JavaCore.getOptions();
        JavaCore.setComplianceOptions(JavaCore.VERSION_1_8, options);
        parser.setCompilerOptions(options);
4. Build ChangeScribe
5. Install as eclipse plugin
6. Create simple java project (or use some existing one, like described above)
7. Add one file (and add it to Git via Eclipse or TortoiseGit), one file untracked and modify one file (i.e. add one method to it).
8. Run ChangeScribe->Commit, select all files -> files are not described correctly.

**Comment by lfcortes12** [comment]
The problem is with Change Distiller because in our work we implemented any changes on this tool. Then we have to clone the version hosted on bitbucked bitbucket.org/lfcortes12/changedistillermodified.git. 

Please, try with this version.

**Comment by TomaszGaweda** [comment]
Dear @lfcortes12, sorry for the delay. After changing Change Distiller version I see that:
1. From GUI: there's no change
![cs_reply_1_gui](https://cloud.githubusercontent.com/assets/8236272/11752482/1b3f0218-a040-11e5-93f6-9796107f7968.png)
1. From shell:
   well, it works better! I don't know the differencies between shell and gui mode, however I can see following message:

```
    1. Changes to package test:  
    1.1. Add a class for test 1. It allows to:
        Get version;
        Handle main
```

So - for our puposes it's ok. 

One thing is that when I have classes with inner classes, I get following exception in console:

```
java.lang.NullPointerException
    at co.edu.unal.colswe.changescribe.core.stereotype.stereotyped.StereotypedType.findSubtypesStereotypes(StereotypedType.java:106)
    at co.edu.unal.colswe.changescribe.core.stereotype.stereotyped.StereotypedType.findStereotypes(StereotypedType.java:99)
    at co.edu.unal.colswe.changescribe.core.stereotype.stereotyped.StereotypeIdentifier.identifyStereotypes(StereotypeIdentifier.java:93)
    at co.edu.unal.colswe.changescribe.core.summarizer.SummarizeChanges.identifyStereotypes(SummarizeChanges.java:537)
    at co.edu.unal.colswe.changescribe.core.summarizer.SummarizeChanges.analyzeForShell(SummarizeChanges.java:131)
    at co.edu.unal.colswe.changescribe.core.summarizer.SummarizeChanges.summarize(SummarizeChanges.java:109)
    at co.edu.unal.colswe.changescribe.core.Main.main(Main.java:147)
    at pl.pwr.ChangeScribeTests.main(ChangeScribeTests.java:16)
```

As far as I can see, it's connected with Eclipse AST implementation. Do you know how to avoid this exception? This exception also causes lack of description for given class.

**Comment by lfcortes12** [comment]
Hi,

Could you attach the class file? Please?

**Comment by lfcortes12** [comment]
I'm trying replicate the bug, but it's not possible. I 
1. Create a simple Java Project
2. Create a new package test
3. Create a new class Test1 with a main method a another version.

That is the result:

![image](https://cloud.githubusercontent.com/assets/1715426/11998147/6a9b8416-aa5f-11e5-90fe-f47c66822c57.png)

The class:

![image](https://cloud.githubusercontent.com/assets/1715426/11998152/868db356-aa5f-11e5-9db3-c4091e58922f.png)

**Comment by TomaszGaweda** [comment]
Dear @lfcortes12, issue seems to be fixed.

Previous problem was probably connected with classpath issues, Eclipse didn't refresh properly the build path. After manual re-check of eclipse build path I had another bug, however connected with Eclipse JDT from p2 repository (you probably have earlier version which works fine; I'm sure it's not a bug in ChangeScribe). After little workaround in ChangeDistiller, ChangeScribe works good :)

Thank you very much for your support!
